### PR TITLE
Bump version, switch to pybind11

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
@isuruf The OSX build passed for 59a7abf, but it now no longer does. Any clue what led to that?

**Comment by isuruf** [comment]
Pocl variant was disabled accidentally in my last PR. I enabled it here. Probably needs a recent clangdev and libcxx for it to work.

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/pyopencl/merge_requests/51 should have a fix for the (legitimate) OSX build failure. That leaves the broken VC9 Python 2.7 build. [This](https://pybind11.readthedocs.io/en/stable/faq.html#working-with-ancient-visual-studio-2009-builds-on-windows) is what the pybind folks have to say about it. Any clue what we might be able to do?

**Comment by isuruf** [comment]
It's something to do with the flags. It seems the extension is built with `-std=c++98`, but looking at setup.py, it seems like it is passing `-std=c++11`

**Comment by inducer** [comment]
Amazing, it builds! Thanks for your help with this. Let's unleash it and see what happens.

**Pull request merged**
