### PR TITLE
Add version 2021.2.1

### PR DESCRIPTION
**Pull request by inducer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by inducer** [comment]
@conda-forge-admin, please rerender

**Comment by isuruf** [comment]
macos failures look like a common error. https://discussions.apple.com/thread/252710156

**Comment by inducer** [comment]
@isuruf Thanks for taking a look! What do you think of 7ac3d40?

**Comment by inducer** [comment]
(Let's hold off on merging that for a bit... @thomasgibson reported a potential new failure.)

**Comment by inducer** [comment]
@conda-forge-admin, please restart ci

**Comment by inducer** [comment]
https://github.com/inducer/pyopencl/pull/474. I'll have to roll 2021.2.1. I'll "yank" this release.

**Comment by inducer** [comment]
@conda-forge-admin, please rerender

**Comment by inducer** [comment]
Drone CI keeps failing with
```
fatal: unable to access 'https://github.com/conda-forge/pyopencl-feedstock.git/': Failed to connect to github.com port 443: Operation timed out
```
Any tips?

**Comment by inducer** [comment]
Uh-oh. Looks like broken version of 2021.2 *somehow* made it onto the archives. I hope it's not something I did.

**Comment by inducer** [comment]
It's causing all sorts of CI breakage, e.g. here: https://github.com/alexfikl/meshmode/pull/8

**Comment by inducer** [comment]
Quite possibly this is due to #63, which I opened by pushing to the feedstock repo instead of a fork. :/

**Comment by inducer** [comment]
Requested removal: https://github.com/conda-forge/admin-requests/pull/263

**Comment by inducer** [comment]
Huh. So that just went then. Interesting. :)

**Pull request merged**
