### PR TITLE
2018.1

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by isuruf** [comment]
@conda-forge-admin, please rerender

**Comment by inducer** [comment]
This build has been pending for two days. That's insane. @isuruf, has anyone asked Travis if they'd be willing to sponsor more resources for conda-forge?

**Comment by isuruf** [comment]
> This build has been pending for two days. That's insane. 

Yeah, last conda-forge travis job was for a commit made 4 days ago.

> @isuruf, has anyone asked Travis if they'd be willing to sponsor more resources for conda-forge?

Some people asked about buying more capacity. See https://github.com/conda-forge/conda-forge.github.io/issues/306

**Comment by inducer** [comment]
>> This build has been pending for two days. That's insane. 
>
> Yeah, last conda-forge travis job was for a commit made 4 days ago.
>
>> @isuruf, has anyone asked Travis if they'd be willing to sponsor more resources for conda-forge?
>
> Some people asked about buying more capacity. See https://github.com/conda-forge/conda-forge.github.io/issues/306

Yikes. Thanks for letting me know.

**Pull request merged**
