### PR TITLE
MNT: Re-rendered with conda-smithy 2.0.1

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
@conda-forge/core I'm encountering this error:

```
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - pyopencl 2016.2.1 py36_1
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

here:

https://travis-ci.org/conda-forge/pyopencl-feedstock/jobs/196450825#L635

but I'm not quite sure what to make of it. Any hints?

**Comment by jjhelmus** [comment]
> but I'm not quite sure what to make of it. Any hints?

Most likely one or more of the dependencies for the recipe has not yet been build for Python 3.6.  From a quick search of the packages it looks like `pytools` is the likely suspect.

**Comment by inducer** [comment]
Thanks for taking a look--that looks like a reasonable suggestion. https://github.com/conda-forge/pytools-feedstock/pull/6

**Comment by jakirkham** [comment]
Tweaked the title to get the linter back.

**Pull request merged**
