### PR TITLE
Use mutex package for osx opencl implementation

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
Ready for review

**Comment by inducer** [comment]
Picked up a conflict. (Sorry for letting this sit for so long.)

**Comment by isuruf** [comment]
I'm thinking whether `osx-opencl-variant=native`, `osx-opencl-variant=pocl` is the way to go. Now that the khronos-icd-loader supports maybe we can drop directly linking to pocl and link to khronos-icd-loader. This way pyopencl can use pocl or oclgrind(which is in conda-forge now) with the icd loader.

**Comment by inducer** [comment]
That would be lovely.

**Comment by inducer** [comment]
(for OSX folks :P)

**Comment by isuruf** [comment]
https://github.com/conda-forge/pyopencl-feedstock/pull/35 uses an ICD loader from osx which is better than having variants

**Pull request closed without merging**
