### PR TITLE
Enable Windows build, rerender

### PR DESCRIPTION
**Pull request by inducer**

### CODE REVIEW

**Comment by inducer** [comment]
@cgohlke I'm having trouble getting PyOpenCL to build with the conda-forge toolchain. I have a feeling you might be more familiar with this. Could you take a look at the "AppVeyor" (Windows) build log? Thanks!

**Comment by cgohlke** [comment]
There are two issues: 
On Python <= 3.4 you can not use Visual Studio 2008 or 2010. They don't have the C++ features required by PyOpenCL. I am using mingwpy for those. 
On Python 3.5 and 3.6, Visual Studio 2015.3 (the current up-to-date version) has a bug that prevents compiling PyOpenCL and PyCUDA. I am using Visual Studio 2015.2 for those.
Hope this helps.

**Comment by inducer** [comment]
@cgohlke Thank you very much for your advice!

I'll see about using `mingwpy`--I saw that that's packaged in conda-forge.

@conda-forge/core Any advice on how I might be able to force the use of VS 2015.2 (instead of the buggy 2015.3)?

**Comment by mwcraig** [comment]
> Any advice on how I might be able to force the use of VS 2015.2 (instead of the buggy 2015.3)?

The folks at appveyor were willing to create a special image that has 2015.2 instead 2015.3, though if IIRC, that image isn't getting updates and you have to ask to have the image made available in your account. See: https://github.com/appveyor/ci/issues/891

**Comment by inducer** [comment]
Looks like I've got Python <=3.4 building using `mingwpy`. For Python >=3.5, `mingwpy` looks almost empty.

@conda-forge/core Looks like I am hitting an issue with Visual Studio 2015 Update 3, and the two available workarounds appear to be (1) build with `mingwpy` (which seems unavailable for Py3.5) or request access to the special AppVeyor image with Update 2 that @mwcraig mentions above (Thanks!). Since I figure this would request would have to be made on behalf of the conda-forge team, I don't feel like I can quite do that. And even if we have required access on the AppVeyor end, it appears to me that switching build images is "frowned upon" (cf. #1481 e.g.). What do you suggest I do in this instance? Thanks in advance.

**Comment by jakirkham** [comment]
I think in both cases it will come down to an [enhancement proposal]( https://github.com/conda-forge/conda-forge-enhancement-proposals ). It is a matter of someone having the time and interest to write one up for each of these cases.

**Comment by inducer** [comment]
https://github.com/appveyor/ci/issues/1196#issuecomment-263972606

**Pull request merged**
