### PR TITLE
MNT: Re-rendered with conda-smithy 2.3.0

### PR DESCRIPTION
**Pull request by isuruf**

### CODE REVIEW

**Comment by isuruf** [comment]
This also adds python 2.7 and 3.6 which were missing because `ocl-icd` was missing for python 2.7 and 3.6 and now it is available.

**Comment by inducer** [comment]
In https://github.com/conda-forge/pyopencl-feedstock/pull/9/commits, I rerendered with 2.3.1. Doesn't look like there were changes there.

Looks good, thx!

**Comment by inducer** [comment]
(I'll wait for the tests to pass before merging.)

**Comment by isuruf** [comment]
Yes, `ocl-icd` was missing for these versions and conda-smithy skips those when that is the case. Now that https://github.com/conda-forge/ocl-icd-feedstock/pull/3 is merged, these changes are shown. Btw, 2.3.1 and 2.3.0 doesn't have any template changes, only changes necessary for feedstock conversions in staged-recipes.

**Comment by inducer** [comment]
Thanks for explaining!

**Comment by inducer** [comment]
(and for your contribution!)

**Pull request merged**
